### ISSUE TITLE
Ajouter le workflow CI

### ISSUE THREAD

**Issue by dbenfouzari** [derniercri/packages#5]
**Is your feature request related to a problem? Please describe.**
I always have to handle CI's Github Actions file.

**Describe the solution you'd like**
Create a `.github/workflows/ci.yml` with
```yml
name: Node.js CI

on:
  push:
    branches: [ develop, master ]
  pull_request:
    branches: [ develop, master ]

jobs:
  check-translations:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          always-auth: true
          registry-url: https://npm.pkg.github.com
          scope: '@derniercri'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: node scripts/check-translations.js

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          always-auth: true
          registry-url: https://npm.pkg.github.com
          scope: '@derniercri'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: yarn lint
      - run: yarn tsc -p .
      - run: yarn test
        env:
          CI: true

  coverage:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          always-auth: true
          registry-url: https://npm.pkg.github.com
          scope: '@derniercri'
      - name: Install dependencies
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - name: CodeClimate coverage
        uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: A_TOKEN
        with:
          coverageCommand: yarn test --coverage

```
